### ISSUE TITLE
PSI demo issue

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#4]
Hi,
Is this PSI(private set intersection) demo?
If each person input a float number, could this demo be changed to compute the sum of the numbers which are encrypted by different public key?

BR

**Comment by ChristianMct** [comment]
Hi, 

> Is this PSI(private set intersection) demo?

This demo implements a PSI, yet in a very simplistic setting where parties trust the server and the poll creator not to collude (since all poll responses are encrypted under the creator's key, this would leak the responses). Removing this assumption is possible by using the threshold schemes (e.g., `lattigo/dbfv`) but  requires a more complex setup and decryption and was left out of the demo for now.

> If each person input a float number, could this demo be changed to compute the sum of the numbers which are encrypted by different public key?

Not directly. To implement such a protocol, you would need a multi-key FHE scheme such as [Chen et al.'s](https://eprint.iacr.org/2019/524). We have [an implementation of this](https://github.com/tuneinsight/lattigo/tree/dev_mkhe) scheme in Lattigo, but it is highly experimental for now and is therefore not on the main branch.

**Comment by macknight** [comment]
> 

Thank you very much for your detailed reply.

BR
