### ISSUE TITLE
key issue

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#5]
Hi,
when running the demo, I would like to confirm that for each row in the demo web page, each row(person) is using different(from other rows(person)) public key to encrypt his own poll data, right?

BR

**Comment by macknight** [comment]
Another question is that in this diagram, where are the evaluation keys?
![image](https://user-images.githubusercontent.com/754293/188536728-d17f864a-7b05-4795-a273-fbef14119415.png)

BR

**Comment by ChristianMct** [comment]
Hi,

For your first question: no. In the current demo, the participant all encrypt their response with the poll creator's pk. The demo implements a simple use-case ([described here](https://homomorphicencryption.org/wp-content/uploads/2020/12/wahc20_demo_christian.pdf)) where the clients and the server are assumed honest and non-colluding. 

For your second question: the evaluation key is part of the cpk. Since evaluation-keys are public-keys themselves, it is common to simplify the notation with cpk=(epk, evk) and give access to this key to both Encrypt and Eval. In other words, to refer to all the needed public-key material as "cpk".

**Comment by macknight** [comment]
> Hi,
> 
> For your first question: no. In the current demo, the participant all encrypt their response with the poll creator's pk. The demo implements a simple use-case ([described here](https://homomorphicencryption.org/wp-content/uploads/2020/12/wahc20_demo_christian.pdf)) where the clients and the server are assumed honest and non-colluding.
> 
> For your second question: the evaluation key is part of the cpk. Since evaluation-keys are public-keys themselves, it is common to simplify the notation with cpk=(epk, evk) and give access to this key to both Encrypt and Eval. In other words, to refer to all the needed public-key material as "cpk".

OK, evaluation key is part of the cpk(collective public key), it's omitted in the legend.
A small question, epk stands for e...what public key? evk stands for evaluation key?

BR

**Comment by ChristianMct** [comment]
In the above, I was referring to the following keys:
`epk`: the collective public *E*ncryption-key
`evk`: the collective public evaluation-key

Note that I used the `epk` notation only in the context of this explanation. In most cases, we use the term "collective public-key" as a shortcut for "collective public encryption-key" because the traditional purpose of a pk in crypto is encryption. FHE introduces the need for additional public material, which we can abstract as being part of "the public key" to simplify the high-level picture. At a lower level, however, it is useful to separate encryption- and evaluation-related keys.
