### ISSUE TITLE
What does LSSS stand for ?

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#6]
Hi,
May I know does LSSS stand for Linear Shamir Secret Sharing?

![image](https://user-images.githubusercontent.com/754293/189050365-c1acd341-77f3-4bd1-b39e-c7eefb1ac433.png)

BR

**Comment by ChristianMct** [comment]
Hi @macknight,

LSSS stands for "Linear Secret-Sharing Scheme". Shamir Secret Sharing is an LSSS.

I'm happy to help with all your questions. It would be great if you could just give them slightly more informative titles (e.g., see the new name for this issue) so that this can also help other along the way. Thanks!
