### ISSUE TITLE
General question on the security assumptions of RLWE

### ISSUE THREAD

**Issue by macknight** [ldsec/lattigo-polls-demo#8]
Hi,
![image](https://user-images.githubusercontent.com/754293/189061797-d253c0f7-63ba-4d18-985f-4e7870d02ebf.png)

We know p1<--U(R), 
then why is p0 indistinguishable from uniform?
And where do we use this p0's indistinguishable characteristic in the decryption process?
I mean "it is hard to find s and p0+sp1~0" is not enough for the security?

BR

**Comment by ChristianMct** [comment]
The indistinguishability properties of p_0 are given by the [RLWE problem](https://en.wikipedia.org/wiki/Ring_learning_with_errors).

You don't need this property for decryption (since the decryptor has access to s).

You need this property to argue that the `u p_0 + e_1` term computed during encryption constitutes a uniformly pseudorandom mask.

**Comment by macknight** [comment]
> 

Hi,
![image](https://user-images.githubusercontent.com/754293/189137524-cefb5ddc-30e4-496c-88c9-12982b9c1855.png)

In encryption process, it seems there's no `u*p_0 + e_1`. Is that typo?
Should we argue `u*p_0 + e_0`  constitutes a uniformly pseudorandom mask? So that the keypoint is that `ct_0` looks as if it's uniformly distributed to protect m, am I right?

BR

**Comment by ChristianMct** [comment]
> In encryption process, it seems there's no u*p_0 + e_1. Is that typo?

Yes, the correct error term is e_0. 

> Should we argue u*p_0 + e_0 constitutes a uniformly pseudorandom mask? So that the keypoint is that ct_0 looks as if it's uniformly distributed to protect m, am I right?

This is correct.
